### ISSUE TITLE
Add itertools to stdx

### ISSUE THREAD

**Issue by LLBlumire** [brson/stdx#15]
Seems like a core part of what people commonly use for functionality with rusts iterators and I believe it meets all the criteria listed

**Comment by brson** [comment]
I actually just removed itertools! I agree it fits the criteria though.

The reason I removed it is because I was writing up examples and didn't see an obvious example for itertools that sold me on the crate being essential. And since I don't think I've ever used itertools myself it seemed like a good candidate to cut - keeping the list concise is important to me.

What's the thing you always reach for itertools for?

**Comment by LLBlumire** [comment]
step,  combinations,  and cartesian_product are my most used.

**Comment by mackwic** [comment]
my personal favorite are, in order, `.sorted()`, `.unique()`, and `.group_by()` (eventually lazy). These are all not-so-frequent operations, but still common enough  in my opinion to justify the presence of itertools in stdx.

**Comment by jswrenn** [comment]
I use [`group_by`](https://docs.rs/itertools/0.5.9/itertools/trait.Itertools.html#method.group_by) frequently for splitting input streams, and I just used [`tuple_windows`](https://docs.rs/itertools/0.5.9/itertools/trait.Itertools.html#method.tuple_windows) for an implementation of bigram [language models](https://en.wikipedia.org/wiki/Language_model#n-gram_models). The combination of Itertools and Rayon feels like having superpowers!

**Comment by Keruspe** [comment]
.join() is really nice to have too

**Comment by iqualfragile** [comment]
yeah, i too feel like itertools is a must have.
if you are programming in a more procedural, less functional style, though, you might never feel any need for them.

**Comment by brson** [comment]
Yeah, ok. It is quite popular and battle tested, and does fill some gaps.

See https://github.com/brson/stdx/blob/master/CONTRIBUTING.md for details on how to add a crate.

Use a simple example based one or some of the above mentioned features.

**Comment by brson** [comment]
Done
