### ISSUE TITLE
Update to Serde 0.9.0

### ISSUE THREAD

**Issue by dtolnay** [brson/stdx#17]
These crates need to be updated first:

- [x] https://github.com/seanmonstar/reqwest/issues/52
- [x] https://github.com/nox/serde_urlencoded/issues/7

**Comment by brson** [comment]
Thanks for the note! I want to do this soon, patches welcome. After serde is upgraded then I hope to ensure that all the stdx crates have proper 'serde' features and serialize implementations.

**Comment by dtolnay** [comment]
Looks like this is done. I filed #22 to follow up on 'serde' features and serialize implementations.
