### ISSUE TITLE
Clarify reasons for using `json` crate

### ISSUE THREAD

**Issue by dtolnay** [brson/stdx#21]
Here is your `json` example from the readme rewritten using `serde_json`. The differences are one type ascription ("let parsed: Value") and a slightly friendlier JSON literal syntax.

I think the readme should show an example that better plays to `json`'s strengths, or else omit this crate since serde and serde_json are already included.

```rust
#[macro_use]
extern crate serde_json;

use serde_json::Value;

fn main() {
    let parsed: Value = serde_json::from_str(r#"
{
    "code": 200,
    "success": true,
    "payload": {
        "features": [
            "awesome",
            "easyAPI",
            "lowLearningCurve"
        ]
    }
}

"#).unwrap();

    let instantiated = json!({
        "code": 200,
        "success": true,
        "payload": {
            "features": [
                "awesome",
                "easyAPI",
                "lowLearningCurve"
            ]
        }
    });

    assert_eq!(parsed, instantiated);
}
```

**Comment by brson** [comment]
Thanks for the suggestion @dtolnay !

**Comment by dtolnay** [comment]
Even more relevant now with stable Serde.

**Comment by brson** [comment]
stdx uses serde_json now.
