### ISSUE TITLE
toml anchor link within github is incorrect

### ISSUE THREAD

**Issue by katamaritaco** [brson/stdx#23]
Within the table of contents at the top of README.md, 'toml = "0.2.1"' is supposed to link to 'https://github.com/brson/stdx#toml', but it instead links to 'https://docs.rs/toml/0.2.1/toml'.

I spent a few minutes trying to figure out why it does that, as the markdown appears to be consistent, but I couldn't find the culprit.

**Comment by brson** [comment]
Fixed. Thanks for the report @katamaritaco
